import { Router } from 'express';
import Attendance from '../models/Attendance.js';
import Employee from '../models/Employee.js';
import HrmsSettings from '../models/HrmsSettings.js';
import { protect } from '../middleware/auth.js';
import { requireBranch } from '../utils/branchScope.js';

const router = Router();
router.use(protect);
router.use(requireBranch);

/**
 * Find the Employee record linked to a User, creating one atomically if it
 * doesn't exist yet. Uses findOneAndUpdate with upsert keyed on `userId`
 * (unique sparse index), so concurrent requests from the same user on first
 * login can never both insert and collide on the empId unique index.
 * empId is now generated by an atomic MasterSequence counter so it is
 * always unique across concurrent inserts.
 */
const findOrCreateEmployee = async (userId, branchId, userData = {}) => {
  // Fast path — employee already exists
  const existing = await Employee.findOne({ userId });
  if (existing) return existing;

  // Generate a guaranteed-unique empId via atomic counter
  const empId = await Employee.generateEmpId();

  // Upsert — only inserts if no document with this userId exists yet.
  // If two requests race here, one wins the insert and the other gets
  // back the winner's document via { new: true }.
  const employee = await Employee.findOneAndUpdate(
    { userId },
    {
      $setOnInsert: {
        userId,
        empId,
        name: userData.name || 'Employee',
        mobile: userData.mobile || '0000000000',
        dateOfJoining: new Date(),
        department: 'Warehouse',
        designation: 'Staff',
        branchId,
        status: 'Active',
      },
    },
    { upsert: true, new: true, setDefaultsOnInsert: true },
  );
  return employee;
};

const calculateAttendanceMetrics = (records, year, month, weeklyOffs = ['Sunday'], dateOfJoining) => {
  const today = new Date();
  const daysInMonth = new Date(year, month, 0).getDate();
  const isCurrentMonth = year === today.getFullYear() && month === today.getMonth() + 1;
  const lastDay = isCurrentMonth ? today.getDate() : daysInMonth;
  const byDay = new Map(records.map(record => [new Date(record.date).getDate(), record]));
  const offDays = new Set(['sunday', ...weeklyOffs.map(day => String(day).toLowerCase())]);
  const joinedAt = dateOfJoining ? new Date(dateOfJoining) : null;
  const joinedDay = joinedAt && !Number.isNaN(joinedAt.getTime())
    ? joinedAt.getFullYear() < year || (joinedAt.getFullYear() === year && joinedAt.getMonth() + 1 < month)
      ? 1
      : joinedAt.getFullYear() === year && joinedAt.getMonth() + 1 === month
        ? joinedAt.getDate()
        : daysInMonth + 1
    : 1;
  const counts = {
    present: 0,
    absent: 0,
    late: 0,
    halfDay: 0,
    leave: 0,
    weekOff: 0,
    holiday: 0,
    onDuty: 0,
    totalMarked: 0,
  };
  const missingDates = [];
  const weekOffDates = [];
  let expectedDays = 0;
  let creditedDays = 0;

  for (let day = joinedDay; day <= lastDay; day++) {
    const date = new Date(year, month - 1, day);
    const record = byDay.get(day);
    const status = record?.status;
    if (record) counts.totalMarked++;
    if (status === 'Week Off') counts.weekOff++;
    if (status === 'Holiday') counts.holiday++;
    if (status === 'Leave') counts.leave++;
    if (status === 'Present') counts.present++;
    if (status === 'Absent') counts.absent++;
    if (status === 'Late') counts.late++;
    if (status === 'Half Day') counts.halfDay++;
    if (status === 'On Duty') counts.onDuty++;

    const weekday = date.toLocaleDateString('en-US', {weekday: 'long'}).toLowerCase();
    const dateKey = `${year}-${String(month).padStart(2, '0')}-${String(day).padStart(2, '0')}`;
    if (offDays.has(weekday)) {
      if (status !== 'Week Off') counts.weekOff++;
      weekOffDates.push(dateKey);
      continue;
    }
    if (status === 'Week Off') {
      weekOffDates.push(dateKey);
      continue;
    }
    if (['Holiday', 'Leave'].includes(status)) continue;

    expectedDays++;
    if (!record) {
      missingDates.push(dateKey);
    } else if (status === 'Present' || status === 'On Duty') {
      creditedDays++;
    } else if (status === 'Late' || status === 'Half Day') {
      creditedDays += 0.5;
    }
  }

  return {
    counts,
    missingDates,
    weekOffDates,
    expectedDays,
    percentage: expectedDays > 0 ? Math.min(100, Math.round((creditedDays / expectedDays) * 100)) : 0,
  };
};

/**
 * POST /attendance/mark
 * Mark attendance for today
 */
router.post('/mark', async (req, res) => {
  try {
    const userId = req.user._id;
    const branchId = req.branchId;

    const employee = await findOrCreateEmployee(userId, branchId, req.user);

    // Get today's date (start of day)
    const today = new Date();
    today.setHours(0, 0, 0, 0);

    // Check if already marked
    const existing = await Attendance.findOne({
      branch: branchId,
      employee: employee._id,
      date: today,
    });

    if (existing) {
      return res.status(400).json({
        success: false,
        message: 'Attendance already marked for today',
        data: existing,
      });
    }

    // Create attendance record
    const attendance = await Attendance.create({
      branch: branchId,
      employee: employee._id,
      date: today,
      punchIn: new Date(),
      punchInLocation: req.body.location || undefined,
      status: 'Present',
      source: 'App',
      markedBy: userId,
    });

    return res.json({
      success: true,
      message: 'Attendance marked successfully',
      data: attendance,
    });
  } catch (error) {
    console.error('Mark attendance error:', error);
    return res.status(500).json({
      success: false,
      message: error.message || 'Failed to mark attendance',
    });
  }
});

/**
 * GET /attendance/today
 * Get today's attendance status
 */
router.get('/today', async (req, res) => {
  try {
    const userId = req.user._id;
    const branchId = req.branchId;

    const employee = await findOrCreateEmployee(userId, branchId, req.user);

    const today = new Date();
    today.setHours(0, 0, 0, 0);

    const attendance = await Attendance.findOne({
      branch: branchId,
      employee: employee._id,
      date: today,
    });

    return res.json({
      success: true,
      data: attendance,
    });
  } catch (error) {
    console.error('Get today attendance error:', error);
    return res.status(500).json({
      success: false,
      message: error.message,
    });
  }
});

/**
 * GET /attendance/calendar
 * Get attendance records for a month (calendar view)
 * Query params: year, month (1-12)
 */
router.get('/calendar', async (req, res) => {
  try {
    const userId = req.user._id;
    const branchId = req.branchId;
    
    const employee = await findOrCreateEmployee(userId, branchId, req.user);

    // Parse year and month from query
    const year = parseInt(req.query.year) || new Date().getFullYear();
    const month = parseInt(req.query.month) || new Date().getMonth() + 1;

    // Get first and last day of month
    const startDate = new Date(year, month - 1, 1);
    startDate.setHours(0, 0, 0, 0);
    
    const endDate = new Date(year, month, 0);
    endDate.setHours(23, 59, 59, 999);

    // Get all attendance records for the month
    const records = await Attendance.find({
      branch: branchId,
      employee: employee._id,
      date: {
        $gte: startDate,
        $lte: endDate,
      },
    }).sort({ date: 1 });

    const hrmsSettings = await HrmsSettings.findOne({branch: branchId}).lean();
    const metrics = calculateAttendanceMetrics(records, year, month, hrmsSettings?.weeklyOffs, employee.dateOfJoining || employee.createdAt);
    const stats = {
      totalDays: metrics.expectedDays,
      present: metrics.counts.present,
      absent: metrics.counts.absent + metrics.missingDates.length,
      halfDay: metrics.counts.halfDay,
      late: metrics.counts.late,
      leave: metrics.counts.leave,
      weekOff: metrics.counts.weekOff,
      holiday: metrics.counts.holiday,
    };
    stats.percentage = metrics.percentage;

    return res.json({
      success: true,
      data: {
        records,
        stats,
        missingDates: metrics.missingDates,
        weekOffDates: metrics.weekOffDates,
        year,
        month,
      },
    });
  } catch (error) {
    console.error('Get calendar error:', error);
    return res.status(500).json({
      success: false,
      message: error.message,
    });
  }
});

/**
 * GET /attendance/summary
 * Get attendance summary for current month
 */
router.get('/summary', async (req, res) => {
  try {
    const userId = req.user._id;
    const branchId = req.branchId;
    
    const employee = await findOrCreateEmployee(userId, branchId, req.user);

    const now = new Date();
    const startOfMonth = new Date(now.getFullYear(), now.getMonth(), 1);
    startOfMonth.setHours(0, 0, 0, 0);
    
    const endOfMonth = new Date(now.getFullYear(), now.getMonth(), now.getDate());
    endOfMonth.setHours(23, 59, 59, 999);

    const records = await Attendance.find({
      branch: branchId,
      employee: employee._id,
      date: {
        $gte: startOfMonth,
        $lte: endOfMonth,
      },
    });

    const hrmsSettings = await HrmsSettings.findOne({branch: branchId}).lean();
    const metrics = calculateAttendanceMetrics(records, now.getFullYear(), now.getMonth() + 1, hrmsSettings?.weeklyOffs, employee.dateOfJoining || employee.createdAt);
    const summary = {
      present: metrics.counts.present,
      absent: metrics.counts.absent + metrics.missingDates.length,
      late: metrics.counts.late,
      leave: metrics.counts.leave,
      halfDay: metrics.counts.halfDay,
      totalMarked: metrics.counts.totalMarked,
      onDuty: metrics.counts.onDuty,
    };

    summary.percentage = metrics.percentage;

    return res.json({
      success: true,
      data: summary,
    });
  } catch (error) {
    console.error('Get summary error:', error);
    return res.status(500).json({
      success: false,
      message: error.message,
    });
  }
});

export default router;
